# Site settings
title: La revolución de la educación colaborativa
email: giovannifranchesco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este es un blog dedicado a la educación colaborativa.
baseurl: "/blogDePrueba7/"  # the subpath of your site, e.g. /blog/
url: "https://github.com/franchescomora/blogDePrueba7" # the base hostname & protocol for your site 
twitter_username: franchescomora
github_username:  franchescomora

# Build settings
markdown: kramdown
